sudo: required

services:
  - docker

archlinux:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    - fontconfig
    - xorg-fonts-encodings
    - xorg-mkfontscale
    - xorg-mkfontdir
  script:
    - "cd /build/ttf-win10 && makepkg"
    - "cd /build/ttf-office && makepkg"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "ttf-win10/ttf-ms-win10-*-any.pkg.tar.xz"
    - "ttf-office/ttf-office-*-any.pkg.tar.xz"
  on:
    tags: true
    all_branches: true
    repo: alongwy/arch-win-fonts
